name:             'BOXFORT'
url:              'http://www.box-fort.com'
markdown:         kramdown
highlighter:      rouge

baseurl:
permalink:        /:title

authors:
 box-fort:
  name: BOXFORT
  display_name: BOXFORT
  email: bustia@box-fort.com
  web: http://www.box-fort.com/

# Server
exclude:          ["LICENSE", "README.md",]
port:             4000

# Prose
prose:
  rooturl: '_posts'
  siteurl: 'http://www.box-fort.com/'
  media: 'assets/img'
